export const INCREMENT="INCREMENT"
export const DECREMENT="DECREMENT"
export const INC_BY_VAL="INC_BY_VAL"

export const FETCH_PRODUCTS="FETCH_PRODUCTS";
export const FILTER_PROD_BY_SIZE="FILTER_PROD_BY_SIZE";
export const SORTINGPRODUCTS="SORTINGPRODUCTS";